In [14]:
import dihz
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
kep = {'system':['Kepler-16','Kepler-34','Kepler-35','Kepler-38','Kepler-64','Kepler-413','Kepler-453','Kepler-1647','Kepler-1661'],
       'm1':[0.6897,1.0479,0.8876,0.949,1.528,0.820,0.944,1.210,0.841],
       'm2':[0.20255,1.0208,0.8094,0.249,0.378,0.5423,0.1951,0.975,0.262],
       'r1':[0.6489,1.1618,1.0284,1.757,1.734,0.7761,0.833,1.7903,0.762],
       'r2':[0.22623,1.0927,0.7861,0.2724,0.408,0.484,0.2150,0.9663,0.276],
       't1':[4450.0,5913.0,5606.0,5640.0,6407.0,4700.0,5527.0,6210.0,5100.0],
       't2':[3311.0,5867.0,5202.0,3325.0,3561.0,3463.0,3226.0,5770.0,3585.0],
       'ab':[0.22431,0.22882,0.17617,0.1469,0.1744,0.10148,0.18539,0.1276,0.187],
       'e_b':[0.15944,0.52087,0.1421,0.1032,0.2117,0.0365,0.0524,0.1593,0.112],
       'a_p':[0.7048,1.0896,0.60345,0.4644,0.634,0.3553,0.7903,2.7205,0.633]}

In [16]:
df = pd.DataFrame(kep)
df

,system,m1,m2,r1,r2,t1,t2,ab,e_b,a_p
0,Kepler-16,0.6897,0.20255,0.6489,0.22623,4450.0,3311.0,0.22431,0.15944,0.70480
1,Kepler-34,1.0479,1.02080,1.1618,1.09270,5913.0,5867.0,0.22882,0.52087,1.08960
2,Kepler-35,0.8876,0.80940,1.0284,0.78610,5606.0,5202.0,0.17617,0.14210,0.60345
3,Kepler-38,0.9490,0.24900,1.7570,0.27240,5640.0,3325.0,0.14690,0.10320,0.46440
4,Kepler-64,1.5280,0.37800,1.7340,0.40800,6407.0,3561.0,0.17440,0.21170,0.63400
5,Kepler-413,0.8200,0.54230,0.7761,0.48400,4700.0,3463.0,0.10148,0.03650,0.35530
6,Kepler-453,0.9440,0.19510,0.8330,0.21500,5527.0,3226.0,0.18539,0.05240,0.79030
7,Kepler-1647,1.2100,0.97500,1.7903,0.96630,6210.0,5770.0,0.12760,0.15930,2.72050
8,Kepler-1661,0.8410,0.26200,0.7620,0.27600,5100.0,3585.0,0.18700,0.11200,0.63300

In [17]:
L1=df.apply(lambda x: x['r1']**(2) * (x['t1']/5800.)**(4), axis=1)
L2=df.apply(lambda x: x['r2']**(2) * (x['t2']/5800.)**(4), axis=1)
df.insert(6,'L2',L2)
df.insert(6,'L1',L1)
df

,system,m1,m2,r1,r2,t1,L1,L2,t2,ab,e_b,a_p
0,Kepler-16,0.6897,0.20255,0.6489,0.22623,4450.0,0.145910,0.005435,3311.0,0.22431,0.15944,0.70480
1,Kepler-34,1.0479,1.02080,1.1618,1.09270,5913.0,1.458083,1.250127,5867.0,0.22882,0.52087,1.08960
2,Kepler-35,0.8876,0.80940,1.0284,0.78610,5606.0,0.923049,0.399876,5202.0,0.17617,0.14210,0.60345
3,Kepler-38,0.9490,0.24900,1.7570,0.27240,5640.0,2.760247,0.008014,3325.0,0.14690,0.10320,0.46440
4,Kepler-64,1.5280,0.37800,1.7340,0.40800,6407.0,4.477186,0.023654,3561.0,0.17440,0.21170,0.63400
5,Kepler-413,0.8200,0.54230,0.7761,0.48400,4700.0,0.259726,0.029771,3463.0,0.10148,0.03650,0.35530
6,Kepler-453,0.9440,0.19510,0.8330,0.21500,5527.0,0.572184,0.004424,3226.0,0.18539,0.05240,0.79030
7,Kepler-1647,1.2100,0.97500,1.7903,0.96630,6210.0,4.212172,0.914566,5770.0,0.12760,0.15930,2.72050
8,Kepler-1661,0.8410,0.26200,0.7620,0.27600,5100.0,0.347119,0.011119,3585.0,0.18700,0.11200,0.63300

In [18]:
#Calculating the habitable zone
M1 = df[['m1', 'r1', 't1','L1']].to_dict('list')
M2 = df[['m2', 'r2', 't2', 'L2']].to_dict('list')
BIN = df[['ab','e_b']].to_dict('list')
num = len(df['m1'])
phzi = np.zeros(num)
phzo = np.zeros(num)
ahzi = np.zeros(num)
ahzo = np.zeros(num)
for i in range(num):
    [PHZI,PHZO]=dihz.circumbinary.PHZ(M1['L1'][i],M1['t1'][i],M1['m1'][i],M2['L2'][i],M2['t2'][i],M2['m2'][i],BIN['ab'][i],BIN['e_b'][i])
    [AHZI,AHZO]=dihz.circumbinary.AHZ(M1['L1'][i],M1['t1'][i],M1['m1'][i],M2['L2'][i],M2['t2'][i],M2['m2'][i],BIN['ab'][i],BIN['e_b'][i])
    phzi[i] = PHZI 
    phzo[i] = PHZO
    ahzi[i] = AHZI
    ahzo[i] = AHZO
n = len(df.loc[2,:])
df.insert(n, 'phzo', phzo)
df.insert(n, 'phzi', phzi)
df.insert(n, 'ahzo', ahzo)
df.insert(n, 'ahzi', ahzi)

In [19]:
df

,system,m1,m2,r1,r2,t1,L1,L2,t2,ab,e_b,a_p,ahzi,ahzo,phzi,phzo
0,Kepler-16,0.6897,0.20255,0.6489,0.22623,4450.0,0.145910,0.005435,3311.0,0.22431,0.15944,0.70480,0.393839,0.732932,0.605523,0.619953
1,Kepler-34,1.0479,1.02080,1.1618,1.09270,5913.0,1.458083,1.250127,5867.0,0.22882,0.52087,1.08960,1.553329,2.731083,1.637924,2.740238
2,Kepler-35,0.8876,0.80940,1.0284,0.78610,5606.0,0.923049,0.399876,5202.0,0.17617,0.14210,0.60345,1.112348,1.978773,1.209110,1.926380
3,Kepler-38,0.9490,0.24900,1.7570,0.27240,5640.0,2.760247,0.008014,3325.0,0.14690,0.10320,0.46440,1.594729,2.823888,1.686508,2.737823
4,Kepler-64,1.5280,0.37800,1.7340,0.40800,6407.0,4.477186,0.023654,3561.0,0.17440,0.21170,0.63400,1.942288,3.382190,2.084204,3.251788
5,Kepler-413,0.8200,0.54230,0.7761,0.48400,4700.0,0.259726,0.029771,3463.0,0.10148,0.03650,0.35530,0.542761,1.001171,0.617348,0.946947
6,Kepler-453,0.9440,0.19510,0.8330,0.21500,5527.0,0.572184,0.004424,3226.0,0.18539,0.05240,0.79030,0.732744,1.302888,0.819633,1.228638
7,Kepler-1647,1.2100,0.97500,1.7903,0.96630,6210.0,4.212172,0.914566,5770.0,0.12760,0.15930,2.72050,2.106433,3.684743,2.195753,3.607335
8,Kepler-1661,0.8410,0.26200,0.7620,0.27600,5100.0,0.347119,0.011119,3585.0,0.18700,0.11200,0.63300,0.591263,1.068993,0.726421,0.971590

In [20]:
#Determine habitability
def determine_hb(a,b,c):
    
    if c>a and c<b:
        return 1 #liveable
    elif c<a or c>b:
        return 2 #unliveable

In [22]:
#reset index
df = df.reset_index(drop=True)
df['phb'] = df.apply(lambda x: determine_hb(x.phzi, x.phzo, x.a_p), axis=1)
ahb = df.apply(lambda x: determine_hb(x.ahzi, x.ahzo, x.a_p), axis=1)
df.insert(16,'ahb',ahb)
df

,system,m1,m2,r1,r2,t1,L1,L2,t2,ab,e_b,a_p,ahzi,ahzo,phzi,phzo,ahb,phb
0,Kepler-16,0.6897,0.20255,0.6489,0.22623,4450.0,0.145910,0.005435,3311.0,0.22431,0.15944,0.70480,0.393839,0.732932,0.605523,0.619953,1,2
1,Kepler-34,1.0479,1.02080,1.1618,1.09270,5913.0,1.458083,1.250127,5867.0,0.22882,0.52087,1.08960,1.553329,2.731083,1.637924,2.740238,2,2
2,Kepler-35,0.8876,0.80940,1.0284,0.78610,5606.0,0.923049,0.399876,5202.0,0.17617,0.14210,0.60345,1.112348,1.978773,1.209110,1.926380,2,2
3,Kepler-38,0.9490,0.24900,1.7570,0.27240,5640.0,2.760247,0.008014,3325.0,0.14690,0.10320,0.46440,1.594729,2.823888,1.686508,2.737823,2,2
4,Kepler-64,1.5280,0.37800,1.7340,0.40800,6407.0,4.477186,0.023654,3561.0,0.17440,0.21170,0.63400,1.942288,3.382190,2.084204,3.251788,2,2
5,Kepler-413,0.8200,0.54230,0.7761,0.48400,4700.0,0.259726,0.029771,3463.0,0.10148,0.03650,0.35530,0.542761,1.001171,0.617348,0.946947,2,2
6,Kepler-453,0.9440,0.19510,0.8330,0.21500,5527.0,0.572184,0.004424,3226.0,0.18539,0.05240,0.79030,0.732744,1.302888,0.819633,1.228638,1,2
7,Kepler-1647,1.2100,0.97500,1.7903,0.96630,6210.0,4.212172,0.914566,5770.0,0.12760,0.15930,2.72050,2.106433,3.684743,2.195753,3.607335,1,1
8,Kepler-1661,0.8410,0.26200,0.7620,0.27600,5100.0,0.347119,0.011119,3585.0,0.18700,0.11200,0.63300,0.591263,1.068993,0.726421,0.971590,1,2

In [23]:
df.to_csv('./kepler_dataset.csv', index=False)