In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('habitable_dataset.csv')
df

,m1,m2,r1,r2,t1,t2,L1,L2,e_b,a_p,inc,status,min_dis,max_dis,ahzi,ahzo,ahb,phzi,phzo,phb
0,0.67,0.33,0.7408,0.3192,4587.1738,3608.2662,0.214719,0.015262,0.20,0.93,0.349066,1,0.846892,1.008940,0.484926,0.896208,0,0.579651,0.826472,2
1,0.69,0.31,0.7656,0.2944,4644.7566,3550.6834,0.241070,0.012173,0.34,1.07,0.698132,1,0.973318,1.155326,0.507601,0.935084,2,0.627018,0.846665,2
2,0.71,0.29,0.7904,0.2696,4702.3394,3493.1006,0.269922,0.009563,0.25,1.16,2.268928,1,1.069090,1.248977,0.531895,0.976763,2,0.634504,0.896201,2
3,0.63,0.37,0.6912,0.3688,4472.0082,3723.4318,0.168852,0.023102,0.17,0.93,1.047198,1,0.854561,1.002811,0.445112,0.828037,2,0.532010,0.770909,2
4,0.53,0.47,0.5672,0.4928,4184.0942,4011.3458,0.087130,0.055564,0.06,0.93,2.792527,1,0.870399,0.985991,0.386943,0.728782,2,0.426733,0.723492,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326687,0.78,0.22,0.8772,0.1828,4903.8792,3291.5608,0.393228,0.003466,0.52,1.22,2.617994,1,1.098917,1.338176,0.627816,1.141360,0,0.774923,1.025167,2
326688,0.77,0.23,0.8648,0.1952,4875.0878,3320.3522,0.373292,0.004092,0.07,0.86,1.745329,1,0.777009,0.941921,0.613181,1.116257,1,0.673680,1.062832,1
326689,0.80,0.20,0.9020,0.1580,4961.4620,3233.9780,0.435652,0.002413,0.50,0.75,0.174533,1,0.623241,0.869252,0.657914,1.192972,0,0.799488,1.078993,0
326690,0.78,0.22,0.8772,0.1828,4903.8792,3291.5608,0.393228,0.003466,0.25,0.90,0.000000,1,0.798659,0.989467,0.627814,1.141359,1,0.723207,1.060231,1
326691,0.58,0.42,0.6292,0.4308,4328.0512,3867.3888,0.122754,0.036687,0.14,0.58,1.396263,1,0.502996,0.654324,0.407709,0.764161,1,0.478084,0.729424,1

In [3]:
train_dataset = df[:300000]
test_dataset = df[300000:]

In [4]:
train_dataset

,m1,m2,r1,r2,t1,t2,L1,L2,e_b,a_p,inc,status,min_dis,max_dis,ahzi,ahzo,ahb,phzi,phzo,phb
0,0.67,0.33,0.7408,0.3192,4587.1738,3608.2662,0.214719,0.015262,0.20,0.93,0.349066,1,0.846892,1.008940,0.484926,0.896208,0,0.579651,0.826472,2
1,0.69,0.31,0.7656,0.2944,4644.7566,3550.6834,0.241070,0.012173,0.34,1.07,0.698132,1,0.973318,1.155326,0.507601,0.935084,2,0.627018,0.846665,2
2,0.71,0.29,0.7904,0.2696,4702.3394,3493.1006,0.269922,0.009563,0.25,1.16,2.268928,1,1.069090,1.248977,0.531895,0.976763,2,0.634504,0.896201,2
3,0.63,0.37,0.6912,0.3688,4472.0082,3723.4318,0.168852,0.023102,0.17,0.93,1.047198,1,0.854561,1.002811,0.445112,0.828037,2,0.532010,0.770909,2
4,0.53,0.47,0.5672,0.4928,4184.0942,4011.3458,0.087130,0.055564,0.06,0.93,2.792527,1,0.870399,0.985991,0.386943,0.728782,2,0.426733,0.723492,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,0.65,0.35,0.7160,0.3440,4529.5910,3665.8490,0.190700,0.018884,0.09,1.15,2.792527,1,1.076249,1.219262,0.464035,0.860421,2,0.539873,0.806216,2
299996,0.56,0.44,0.6044,0.4556,4270.4684,3924.9716,0.107359,0.043531,0.10,1.00,0.872665,1,0.936574,1.061182,0.397246,0.746330,2,0.455111,0.723671,2
299997,0.79,0.21,0.8896,0.1704,4932.6706,3262.7694,0.414005,0.002908,0.52,0.72,1.396263,1,0.594960,0.839153,0.642729,1.166937,0,0.788930,1.050608,0
299998,0.54,0.46,0.5796,0.4804,4212.8856,3982.5544,0.093511,0.051303,0.08,0.71,2.792527,1,0.647550,0.767683,0.389634,0.733365,0,0.436195,0.722209,0
299999,0.78,0.22,0.8772,0.1828,4903.8792,3291.5608,0.393228,0.003466,0.37,1.33,1.919862,1,1.220457,1.438308,0.627814,1.141359,2,0.746901,1.043456,2

In [5]:
train_dataset.to_csv('train_dataset.csv',index=False)

In [6]:
test_dataset

,m1,m2,r1,r2,t1,t2,L1,L2,e_b,a_p,inc,status,min_dis,max_dis,ahzi,ahzo,ahb,phzi,phzo,phb
300000,0.54,0.46,0.5796,0.4804,4212.8856,3982.5544,0.093511,0.051303,0.34,0.75,3.141593,1,0.670080,0.822320,0.389635,0.733367,0,0.459994,0.718806,0
300001,0.56,0.44,0.6044,0.4556,4270.4684,3924.9716,0.107359,0.043531,0.09,1.42,1.221730,1,1.358155,1.480565,0.397246,0.746330,2,0.454061,0.724033,2
300002,0.68,0.32,0.7532,0.3068,4615.9652,3579.4748,0.227593,0.013655,0.12,0.51,2.967060,1,0.428046,0.585079,0.496049,0.915277,0,0.576702,0.853443,0
300003,0.79,0.21,0.8896,0.1704,4932.6706,3262.7694,0.414005,0.002908,0.35,1.29,1.919862,1,1.180093,1.398944,0.642727,1.166935,2,0.756793,1.071928,2
300004,0.70,0.30,0.7780,0.2820,4673.5480,3521.8920,0.255173,0.010812,0.13,1.44,1.221730,1,1.356157,1.522624,0.519553,0.955588,2,0.600777,0.890990,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326687,0.78,0.22,0.8772,0.1828,4903.8792,3291.5608,0.393228,0.003466,0.52,1.22,2.617994,1,1.098917,1.338176,0.627816,1.141360,0,0.774923,1.025167,2
326688,0.77,0.23,0.8648,0.1952,4875.0878,3320.3522,0.373292,0.004092,0.07,0.86,1.745329,1,0.777009,0.941921,0.613181,1.116257,1,0.673680,1.062832,1
326689,0.80,0.20,0.9020,0.1580,4961.4620,3233.9780,0.435652,0.002413,0.50,0.75,0.174533,1,0.623241,0.869252,0.657914,1.192972,0,0.799488,1.078993,0
326690,0.78,0.22,0.8772,0.1828,4903.8792,3291.5608,0.393228,0.003466,0.25,0.90,0.000000,1,0.798659,0.989467,0.627814,1.141359,1,0.723207,1.060231,1
326691,0.58,0.42,0.6292,0.4308,4328.0512,3867.3888,0.122754,0.036687,0.14,0.58,1.396263,1,0.502996,0.654324,0.407709,0.764161,1,0.478084,0.729424,1

In [7]:
test_dataset.to_csv('test_dataset.csv', index=False)